site_name: X-LAB Plotting Manager
site_description: "Graphical user interface for scientific data management and analysis"
repo_url: https://github.com/Allyson-Robert/X-LAB_Plotting_Manager

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - Getting started: getting_started.md
  - Dataspecs: dataspecs.md
  - Logging & debugging: logging.md
  - API:
      - GUI:
          - Windows: api/gui/windows_and_dialogs.md
          - Plot Manager: api/gui/plot_manager.md
          - Utils: api/gui/utils.md
      - Contracts:
          - Data:
              - Data Types: api/contracts/data/data_types.md
              - Data Processors: api/contracts/data/data_processors.md
          - Plotters:
              - Plotter: api/contracts/plotters/plotter.md
              - PlotterOptions: api/contracts/plotters/plotter_options.md
          - Devices: api/contracts/devices.md
          - File Readers: api/contracts/file_readers.md
          - Observable: api/contracts/observable.md
      - Utils:
          - Class Utils: api/utils/class_utils.md
          - Errors: api/utils/errors.md
          - Others: api/utils/others.md
      - DataSpec: api/dataspec_manager.md
